Repository tsedio/tsed, pull requests merged in 2022-10, with the labels that each got.

#2121 fix(prisma): fix prisma @tsED.Ignore() parsing
  packages/orm/prisma/src/generator/utils/parseDocumentationAttributes.spec.ts
  packages/orm/prisma/src/generator/utils/parseDocumentationAttributes.ts
Labels: :bug: bug

#2118 feat(schema): support AdditionalProperties with model
  packages/specs/schema/src/decorators/common/additionalProperties.spec.ts
  packages/specs/schema/src/domain/JsonSchema.ts
Labels: hacktoberfest-accepted

#2120 fix(oidc-provider): fix documentation to create and route custom interaction
  docs/tutorials/oidc.md
  packages/security/oidc-provider/src/domain/OidcInteractionOptions.ts
  packages/security/oidc-provider/src/services/OidcInteractionContext.ts
  packages/security/oidc-provider/src/services/OidcProvider.ts
  packages/security/oidc-provider/test/app/controllers/oidc/InteractionsCtrl.ts
  packages/security/oidc-provider/test/app/interactions/CustomInteraction.ts
  packages/security/oidc-provider/test/app/views/custom.ejs
  packages/security/oidc-provider/test/app/views/forms/custom-form.ejs
  packages/security/oidc-provider/test/app/views/partials/login-help.ejs
Labels: hacktoberfest-accepted

#2129 fix(oidc-provider): fix prompt mapping between methods and decorators parameters
  .gflowrc
  packages/security/oidc-provider/src/services/OidcProvider.spec.ts
  packages/security/oidc-provider/src/services/OidcProvider.ts
Labels: hacktoberfest-accepted

#2132 fix(mongoose): remove protected key _id in createSchema and allow custom _id type definition
  packages/orm/mongoose/src/decorators/objectID.ts
  packages/orm/mongoose/src/utils/buildMongooseSchema.spec.ts
  packages/orm/mongoose/src/utils/createSchema.spec.ts
  packages/orm/mongoose/src/utils/createSchema.ts
Labels: hacktoberfest-accepted

#2133 fix: use Prompt priority
  packages/security/oidc-provider/src/services/OidcProvider.ts
Labels: hacktoberfest-accepted

#2131 fix(platform-params): improve documentation around validator/json-mapper when input param decorator is used
  .github/workflows/build.yml
  docs/docs/controllers.md
  docs/docs/snippets/controllers/params-advanced-usage.ts
  docs/docs/snippets/pipes/body-params.ts
  docs/docs/snippets/pipes/use-params.ts
  docs/getting-started/README.md
  docs/getting-started/start-with-cli.md
  packages/platform/common/src/decorators/params/error.ts
  packages/platform/common/src/decorators/params/next.ts
  packages/platform/common/src/decorators/params/request.ts
  packages/platform/platform-koa/src/decorators/ctx.ts
  packages/platform/platform-params/src/decorators/bodyParams.ts
  packages/platform/platform-params/src/decorators/context.ts
  packages/platform/platform-params/src/decorators/cookies.ts
  packages/platform/platform-params/src/decorators/headerParams.ts
  packages/platform/platform-params/src/decorators/locals.ts
  packages/platform/platform-params/src/decorators/pathParams.ts
  packages/platform/platform-params/src/decorators/queryParams.ts
  packages/platform/platform-params/src/decorators/session.ts
  packages/platform/platform-params/src/decorators/useParam.spec.ts
  packages/platform/platform-params/src/decorators/useParam.ts
  packages/platform/platform-params/src/domain/ParamOptions.ts
  packages/platform/platform-params/src/utils/mapParamsOptions.ts
  packages/third-parties/socketio/src/class/SocketHandlersBuilder.spec.ts
  packages/third-parties/socketio/src/class/SocketHandlersBuilder.ts
  packages/third-parties/socketio/src/decorators/args.spec.ts
  packages/third-parties/socketio/src/decorators/args.ts
  packages/third-parties/socketio/src/interfaces/SocketParamMetadata.ts
Labels: hacktoberfest, hacktoberfest-accepted
